{% set version = "6.7.2" %}
{% set version_major_minor_match = '.'.join(version.split('.')[0:3]) %}

package:
  name: pyside6
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-{{ version }}-src/pyside-setup-everywhere-src-{{ version }}.tar.xz
  sha256: 3a2b0d0d6e78c9aa5ddc7f06ca4b6f11a3fe14560baeb148eea53b5d98e368c7
  patches:
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - patches/pyi_osx.patch
    - patches/qfp_osx.patch
    # https://bugreports.qt.io/browse/PYSIDE-2057
    - patches/do_not_store_build_time_compiler.patch
    # change tools module location
    - patches/tools.patch
    # https://bugreports.qt.io/browse/PYSIDE-2192
    # backport of PyOS_InputHook downloaded from https://codereview.qt-project.org/c/pyside/pyside-setup/+/454254
    # should be removed for 6.7.3+
    - patches/1864c79.diff

build:
  number: 1
  # 6.8.x is required for python > 3.12
  skip: true  # [py<39 or py>312]
  skip: true  # [osx and x86_64]
  entry_points:
    - pyside6-rcc = PySide6.scripts.pyside_tool:rcc
    - pyside6-uic = PySide6.scripts.pyside_tool:uic

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - patch        # [unix]
    - msys2-patch  # [win]
  host:
    - python
    - setuptools
    - expat {{ expat }}  # [linux and not aarch64]
    - gtk2 2.24  # [linux]
    - libxcb {{ libxcb }}  # [linux]
    - libxslt {{ libxslt }}
    - libxml2 {{ libxml2 }}
    - mypy
    - numpy {{ numpy }}
    - qtbase-devel {{ version }}
    - qtdeclarative {{ version }}
    - qtshadertools {{ version }}
    - qtsvg {{ version }}
    - qttools {{ version }}
    - qtwebchannel {{ version }}
    - qtwebengine {{ version }}
    - qtwebsockets {{ version }}
    - clangdev {{ cxx_compiler_version }}  # [osx]
    - clangdev 17.0  # [not osx]
    - zstd {{ zstd }}
    - libgl-devel                        # [linux]
    - libegl-devel                       # [linux]
    - libopengl-devel                    # [linux]
    - libvulkan-headers                  # [not osx]
    - libvulkan-loader                   # [not osx]

  run:
    - python
    # Pulled in transitively through clangdev but is a weak export so we have to add it here.
    - {{ pin_compatible("libclang13", max_pin="x.x") }}
  run_constrained:
    - qt5compat {{ version }}
    - qtimageformats {{ version }}
    - qttranslations {{ version }}

test:
  requires:
    # TODO: map CDT alsa-lib-devel to new X11 package
    # - { cdt('alsa-lib-devel') }
    # TODO: map CDT cups-devel to new X11 package
    # - { cdt('cups-devel') }
    # TODO: map CDT gtkmm24-devel to new X11 package
    # - { cdt('gtkmm24-devel') }
    # TODO: map CDT libdrm-devel to new X11 package
    # - { cdt('libdrm-devel') }
    # TODO: map CDT libselinux-devel to new X11 package
    # - { cdt('libselinux-devel') }
    # TODO: map CDT libxkbfile-devel to new X11 package
    # - { cdt('libxkbfile-devel') }
    # TODO: map CDT mesa-libgbm-devel to new X11 package
    # - { cdt('mesa-libgbm-devel') }
    # TODO: map CDT mesa-libegl-devel to new X11 package
    # - { cdt('mesa-libegl-devel') }
    # TODO: map CDT pciutils-devel to new X11 package
    # - { cdt('pciutils-devel') }
  imports:
    - PySide6

about:
  home: https://wiki.qt.io/Qt_for_Python
  license: LGPL-3.0-only
  license_file: LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Python bindings for Qt
  description: |
    PySide6 is the official Python module from the Qt for Python project, which provides access to the complete
    Qt 6.0+ framework.
  doc_url: https://doc.qt.io/qtforpython-6
  dev_url: https://code.qt.io/cgit/pyside/pyside-setup.git

extra:
  recipe-maintainers:
    - jan-janssen
    - jschueller