{% set name = "pyside6" %}
{% set version = "6.7.3" %}
{% set version_major_minor_match = '.'.join(version.split('.')[0:3]) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/QtForPython/{{ name }}/PySide6-{{ version }}-src/{{ name }}-setup-everywhere-src-{{ version }}.tar.xz
  sha256: a4c414be013d5051a2d10a9a1151e686488a3172c08a57461ea04b0a0ab74e09
  patches:
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - patches/pyi_osx.patch
    - patches/qfp_osx.patch
    # https://bugreports.qt.io/browse/PYSIDE-2057
    - patches/do_not_store_build_time_compiler.patch
    # change tools module location
    - patches/tools.patch
    # TODO: Remove this patch once we switch to a setuptools-based build instead of directly calling CMake.
    - patches/add-opengl-header-path.patch  # [linux]

build:
  number: 1
  # 6.8.x is required for python > 3.12
  skip: true  # [py<39 or py>312]
  skip: true  # [osx and x86_64]
  entry_points:
    - pyside6-rcc = PySide6.scripts.pyside_tool:rcc
    - pyside6-uic = PySide6.scripts.pyside_tool:uic

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - patch        # [unix]
    - msys2-patch  # [win]
  host:
    - python
    - setuptools
    - gtk2 2.24                            # [linux]
    - libxslt {{ libxslt }}
    - libxml2 {{ libxml2 }}
    - mypy
    # https://code.qt.io/cgit/pyside/pyside-setup.git/tree/requirements.txt?h=6.7.3
    - numpy 1.26.3
    - qtbase-devel {{ qt }}
    - qtdeclarative {{ qt }}
    - qtshadertools {{ qt }}
    - qtsvg {{ qt }}
    - qttools {{ qt }}
    - qtwebchannel {{ qt }}
    - qtwebengine {{ qt }}
    - qtwebsockets {{ qt }}
    - clangdev {{ cxx_compiler_version }}  # [osx]
    - clangdev 14.0                        # [not osx]
    - zstd {{ zstd }}
    - libgl-devel {{ libgl }}              # [linux]
    - libglx-devel {{ libglx }}            # [linux]
  run:
    - python
    # Pulled in transitively through clangdev but is a weak export so we have to add it here.
    - {{ pin_compatible("libclang13", max_pin="x.x") }}
  run_constrained:
    - qt5compat {{ version }}
    - qtimageformats {{ version }}
    - qttranslations {{ version }}

test:
  imports:
    - PySide6
    - PySide6.QtCore
    - PySide6.QtDBus
    - PySide6.QtDesigner
    - PySide6.QtGui
    - PySide6.QtHelp
    - PySide6.QtNetwork
    - PySide6.QtOpenGL
    - PySide6.QtOpenGLWidgets
    - PySide6.QtPdf
    - PySide6.QtPdfWidgets
    - PySide6.QtPrintSupport
    - PySide6.QtQml
    - PySide6.QtQuick
    - PySide6.QtQuickWidgets
    - PySide6.QtSql
    - PySide6.QtSvg
    - PySide6.QtSvgWidgets
    - PySide6.QtTest
    - PySide6.QtWebChannel
    - PySide6.QtWebEngineCore
    - PySide6.QtWebEngineQuick
    - PySide6.QtWebEngineWidgets
    - PySide6.QtWebSockets
    - PySide6.QtWidgets
    - PySide6.QtXml
  requires:
    - pip
    - qtbase-devel {{ qt }}
  commands:
    - pip check
    - shiboken6 --help
    - pyside6-rcc -help
    - pyside6-uic -help

about:
  home: https://wiki.qt.io/Qt_for_Python
  license: LGPL-3.0-only
  license_file: LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Python bindings for Qt
  description: |
    PySide6 is the official Python module from the Qt for Python project, which provides access to the complete
    Qt 6.0+ framework.
  doc_url: https://doc.qt.io/qtforpython-6
  dev_url: https://code.qt.io/cgit/pyside/pyside-setup.git

extra:
  recipe-maintainers:
    - jan-janssen
    - jschueller
