{% set version = "6.9.2" %}
{% set version_major_minor_match = '.'.join(version.split('.')[0:3]) %}

package:
  name: pyside6
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-{{ version }}-src/pyside-setup-everywhere-src-{{ version }}.tar.xz
  sha256: 9ec087465342bdc9dbe492a30e58fdbbc5448655deacf5982a0fe7123f59222d
  patches:
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - patches/pyi_osx.patch
    - patches/qfp_osx.patch
    # https://bugreports.qt.io/browse/PYSIDE-2057
    - patches/do_not_store_build_time_compiler.patch
    # change tools module location
    - patches/tools.patch
    # TODO: Remove this patch once we switch to a setuptools-based build instead of directly calling CMake.
    - patches/add-opengl-header-path.patch  # [linux]

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - pyside6-rcc = PySide6.scripts.pyside_tool:rcc
    - pyside6-uic = PySide6.scripts.pyside_tool:uic

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - setuptools
    - gtk2 2.24                            # [linux]
    - libxslt {{ libxslt }}
    - libxml2 {{ libxml2 }}
    # https://code.qt.io/cgit/pyside/pyside-setup.git/tree/requirements.txt?h=6.9.2
    - mypy >=1.15.0
    - numpy 2.0.2                          # [py<310]
    - numpy 2.1.3                          # [py>39]
    - qtbase-devel {{ qt }}
    - qtdeclarative {{ qt }}
    - qtshadertools {{ qt }}
    - qtsvg {{ qt }}
    - qttools {{ qt }}
    - qtwebchannel {{ qt }}
    - qtwebengine {{ qt }}
    - qtwebsockets {{ qt }}
    - clangdev {{ cxx_compiler_version }}  # [osx]
    - clangdev 17.0                        # [not osx]
    - libclang
    - zstd {{ zstd }}
    - libgl-devel {{ libgl }}              # [linux]
    - libglx-devel {{ libglx }}            # [linux]
    - libvulkan-headers {{ libvulkan }}    # [not osx]
    - libvulkan-loader {{ libvulkan }}     # [not osx]
  run:
    - python

test:
  imports:
    - PySide6
    - PySide6.QtCore
    - PySide6.QtDBus
    - PySide6.QtDesigner
    - PySide6.QtGui
    - PySide6.QtHelp
    - PySide6.QtNetwork
    - PySide6.QtOpenGL
    - PySide6.QtOpenGLWidgets
    - PySide6.QtPdf
    - PySide6.QtPdfWidgets
    - PySide6.QtPrintSupport
    - PySide6.QtQml
    - PySide6.QtQuick
    - PySide6.QtQuickWidgets
    - PySide6.QtSql
    - PySide6.QtSvg
    - PySide6.QtSvgWidgets
    - PySide6.QtTest
    - PySide6.QtWebChannel
    - PySide6.QtWebEngineCore
    - PySide6.QtWebEngineQuick
    - PySide6.QtWebEngineWidgets
    - PySide6.QtWebSockets
    - PySide6.QtWidgets
    - PySide6.QtXml
  requires:
    - pip
    - qtbase-devel {{ qt }}
  commands:
    - pip check
    - shiboken6 --help
    - pyside6-rcc -help
    - pyside6-uic -help

about:
  home: https://wiki.qt.io/Qt_for_Python
  license: LGPL-3.0-only
  license_file: LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Python bindings for Qt
  description: |
    PySide6 is the official Python module from the Qt for Python project, which provides access to the complete
    Qt 6.0+ framework.
  doc_url: https://doc.qt.io/qtforpython-6
  dev_url: https://code.qt.io/cgit/pyside/pyside-setup.git

extra:
  skip-lints:
    - has_run_test_and_commands
  recipe-maintainers:
    - jan-janssen
    - jschueller
